[ansible_target]
10.151.13.207

[ansible_target:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3

[rocky]
default ansible_host=192.168.121.210

[rocky:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_keys/vagrant.key.rsa
ansible_python_interpreter=/usr/bin/python3.9
ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa'
